{{- if eq .Values.backend "infisical" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
stringData:
  clientId: {{ .Values.universalAuth.clientId }}
  clientSecret: {{ .Values.universalAuth.clientSecret }}
{{- end }}
