{{- $ns := .Values.localSecrets.namespace }}
{{- range $name, $data := .Values.localSecrets.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $ns }}
stringData:
  {{- range $key, $value := $data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
