apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.stack.name }}-apps
  namespace: argocd
spec:
  project: {{ .Values.stack.name }}
  source:
    repoURL: '{{ .Values.source.repoURL }}'
    targetRevision: '{{ .Values.source.targetRevision }}'
    path: apps
    helm:
      valuesObject:
        stack:
          name: '{{ .Values.stack.name }}'
        autosync:
          enabled: {{ .Values.autosync.enabled }}
        cluster:
          domain: '{{ .Values.cluster.domain }}'
        oauth:
          enabled: {{ .Values.oauth.enabled }}
          authUrl: '{{ .Values.oauth.authUrl }}'
          signinUrl: '{{ .Values.oauth.signinUrl | default (printf "https://auth.%s/?rd=$scheme://$host$request_uri" .Values.cluster.domain) }}'
          responseHeaders: '{{ .Values.oauth.responseHeaders }}'
        source:
          repoURL: '{{ .Values.source.repoURL }}'
          targetRevision: '{{ .Values.source.targetRevision }}'
        secrets:
          backend:
            kubernetes:
              namespace: '{{ .Values.secrets.backend.kubernetes.namespace | default (printf "%s-secrets" .Values.stack.name) }}'
            infisical:
              endpoint: '{{ .Values.secrets.backend.infisical.endpoint }}'
              projectSlug: '{{ .Values.secrets.backend.infisical.projectSlug }}'
              environment: '{{ .Values.secrets.backend.infisical.environment }}'
              secretsPath: '{{ .Values.secrets.backend.infisical.secretsPath }}'
              credentialsSecret: '{{ .Values.secrets.backend.infisical.credentialsSecret | default (printf "%s-credentials" .Values.stack.name) }}'
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    {{- if .Values.autosync.enabled }}
    automated:
      prune: true
    {{- end }}
