apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.stack.name }}-apps
  namespace: argocd
spec:
  project: {{ .Values.stack.name }}
  source:
    repoURL: '{{ .Values.source.repoURL }}'
    targetRevision: '{{ .Values.source.targetRevision }}'
    path: apps
    helm:
      valuesObject:
{{ merge (omit .Values "source") (dict "source" (omit .Values.source "username" "password")) | toYaml | indent 8 }}

  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    {{- if .Values.autosync.enabled }}
    automated:
      prune: true
    {{- end }}
