apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-helm"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: {{ .Values.helm.repoURL }}
  enableOCI: "true"
  username: {{ .Values.source.username }}
  password: {{ .Values.source.password }}
