apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-git"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.source.repoURL }}
  username: {{ .Values.source.username }}
  password: {{ .Values.source.password }}
